name: junitxml-to-markdown test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mas0061/junitxml-to-markdown@main
        with:
          junitxml-path: "./examples/*.xml"
        id: junitxml-to-markdown
      - run: cat ${{ steps.junitxml-to-markdown.outputs.markdown-path }}
